### PR TITLE
add UFZ Leipzig

### PR DESCRIPTION
**Pull request by bernt-matthias**

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Just stumbled over this repo accidentally. @bgruening and @hrhotz can/should we mention this repo in the small scale galaxy admins group next time? 

Maybe also integrate a note in the Galaxy admin training?

**Comment by bernt-matthias** [comment]
Somehow my coordinates seem incorrect.

**Comment by hrhotz** [comment]
sure, we can mention this during the next small scale galaxy admins group meeting - do you mind adding it to the rolling minutes

on the other hand, it is probably completely out-of-date. The last change was 6 years ago.....@bgruening shall we make an effort to up-date this, i.e. send out a call to the community?

on a similar note: what about this one: https://www.google.com/maps/d/u/0/viewer?mid=1r8LJy6la-JeIrg23aZjpwVNjJDE&ll=47.12664475608175%2C8.543452195446978&z=8   this is also pretty much out-of-date, isn't-it?

these kind of directories are always out-of-date and require a lot of (manual) maintenance

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
I do think something like that is useful for outreach ... that's all that I can say.

**Comment by lldelisle** [comment]
I love the idea of this repo. Why not simply contacting all people listed here and asking if they can check the info?

**Comment by bgruening** [comment]
We can do that ...
I'm also happy to move this repo to usealaxy-eu or galaxyproject.

**Comment by bgruening** [comment]
In the meantime I have added you all to the repo, please accept the invite.

**Comment by lldelisle** [comment]
I feel like it make more sense to move it to galaxyproject and it will gain in visibility (not saying that your git user lack of visibility :wink: )

**Comment by bgruening** [comment]
It is now under the galaxyproject.

**Pull request merged**
